# image will be published to ghcr.io/<user>/<name>
name: kfm
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    #repos:
    #  - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo # COSMIC
    install:
      - rsnapshot
      - yakuake
      - fish
      # fonts
      - adobe-source-code-pro-fonts
      - cascadia-code-nf-fonts
      - cascadia-mono-nf-fonts
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - google-roboto-condensed-fonts
      - google-roboto-fonts
      - google-roboto-mono-fonts
      - google-roboto-slab-fonts
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - powerline-fonts
      - rsms-inter-fonts
    #remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - install_huion_driver.sh

